import { DrinkType } from '@/types/models';

export const DRINK_NAMES: Record<DrinkType, string[]> = {
  beer: [
    'IPA', 'Double IPA', 'Hazy IPA', 'Session IPA', 'West Coast IPA',
    'Pale Ale', 'American Pale Ale', 'Amber Ale', 'Blonde Ale', 'Cream Ale',
    'Stout', 'Imperial Stout', 'Milk Stout', 'Oatmeal Stout', 'Dry Irish Stout',
    'Porter', 'Robust Porter', 'Brown Ale',
    'Lager', 'Pilsner', 'Czech Pilsner', 'Helles', 'Märzen', 'Vienna Lager',
    'Bock', 'Doppelbock', 'Maibock',
    'Hefeweizen', 'Weizenbock', 'Dunkelweizen', 'Dunkel', 'Kölsch',
    'Saison', 'Farmhouse Ale', 'Belgian Tripel', 'Belgian Dubbel', 'Belgian Quad',
    'Sour', 'Gose', 'Berliner Weisse', 'Lambic', 'Gueuze', 'Flanders Red',
    'Fruit Beer', 'Smoked Beer', 'Barleywine', 'Old Ale', 'Scotch Ale',
    'Red Ale', 'Irish Red Ale',
  ],
  wine: [
    'Cabernet Sauvignon', 'Merlot', 'Pinot Noir', 'Syrah / Shiraz', 'Zinfandel',
    'Malbec', 'Sangiovese', 'Tempranillo', 'Grenache', 'Nebbiolo', 'Montepulciano',
    'Chardonnay', 'Sauvignon Blanc', 'Pinot Grigio', 'Riesling', 'Moscato',
    'Gewürztraminer', 'Viognier', 'Chenin Blanc', 'Albariño', 'Grüner Veltliner',
    'Champagne', 'Prosecco', 'Cava', 'Crémant',
    'Rosé', 'White Zinfandel',
    'Port', 'Sherry', 'Madeira', 'Dessert Wine', 'Ice Wine',
    'Mead', 'Lambrusco', 'Sparkling Red',
  ],
  cocktail: [
    'Margarita', 'Frozen Margarita', 'Tommy\'s Margarita',
    'Mojito', 'Old Fashioned', 'Negroni', 'Manhattan', 'Rob Roy',
    'Whiskey Sour', 'Amaretto Sour', 'Daiquiri', 'Frozen Daiquiri',
    'Martini', 'Dirty Martini', 'Dry Martini', 'Espresso Martini',
    'Gin & Tonic', 'Moscow Mule', 'Kentucky Mule', 'Dark & Stormy',
    'Cosmopolitan', 'Aperol Spritz', 'Paloma', 'Tequila Sunrise',
    'Long Island Iced Tea', 'Tom Collins', 'John Collins',
    'Rum & Coke', 'Cuba Libre', 'Vodka Soda', 'Vodka Tonic',
    'Piña Colada', 'Bloody Mary', 'Screwdriver', 'Harvey Wallbanger',
    'Sidecar', 'Gimlet', 'Bee\'s Knees', 'French 75',
    'Kir Royale', 'Bellini', 'Peach Bellini',
    'Jungle Bird', 'Last Word', 'Paper Plane', 'Penicillin',
    'Sazerac', 'Vieux Carré', 'Aviation', 'Clover Club',
    'Caipirinha', 'Pisco Sour', 'Singapore Sling',
    'Porn Star Martini', 'Sex on the Beach', 'Bay Breeze', 'Madras',
    'Rum Punch', 'Planter\'s Punch', 'Mai Tai', 'Zombie',
    'Spritz', 'Hugo Spritz', 'Lemon Drop', 'Kamikaze',
  ],
  spirit: [
    'Bourbon', 'Tennessee Whiskey', 'Rye Whiskey',
    'Scotch Whisky', 'Single Malt Scotch', 'Blended Scotch',
    'Irish Whiskey', 'Japanese Whisky', 'Canadian Whisky',
    'Vodka', 'Flavored Vodka',
    'London Dry Gin', 'Old Tom Gin', 'Sloe Gin',
    'White Rum', 'Dark Rum', 'Aged Rum', 'Spiced Rum', 'Overproof Rum',
    'Blanco Tequila', 'Reposado Tequila', 'Añejo Tequila', 'Extra Añejo',
    'Mezcal', 'Sotol', 'Raicilla',
    'Cognac', 'Armagnac', 'Calvados', 'Brandy',
    'Grappa', 'Pisco',
    'Sake', 'Shochu', 'Soju', 'Baijiu',
    'Absinthe', 'Amaro', 'Aperitivo', 'Digestivo',
    'Triple Sec', 'Curaçao', 'Grand Marnier', 'Cointreau',
    'Amaretto', 'Baileys Irish Cream', 'Kahlúa', 'Frangelico',
    'Campari', 'Aperol', 'Jägermeister', 'Sambuca', 'Schnapps',
    'Vermouth', 'Dry Vermouth', 'Sweet Vermouth',
  ],
  cider: [
    'Dry Hard Cider', 'Sweet Hard Cider', 'Semi-Sweet Cider',
    'Sparkling Cider', 'Still Cider',
    'Rosé Cider', 'Hopped Cider', 'Spiced Cider',
    'Pear Cider (Perry)', 'Ice Cider',
    'Farmhouse Cider', 'Heritage Cider', 'Craft Cider',
    'Fruit Cider', 'Berry Cider', 'Tropical Cider',
  ],
  seltzer: [
    'Hard Seltzer', 'Fruit Hard Seltzer', 'Tropical Hard Seltzer',
    'Berry Hard Seltzer', 'Citrus Hard Seltzer', 'Mango Hard Seltzer',
    'Ranch Water', 'Sparkling Hard Seltzer',
  ],
  water: [
    'Still Water', 'Sparkling Water', 'Mineral Water', 'Tap Water',
    'Coconut Water', 'Lemon Water', 'Cucumber Water', 'Infused Water',
  ],
  soft_drink: [
    'Cola', 'Diet Cola', 'Zero Sugar Cola', 'Lemon-Lime Soda',
    'Ginger Ale', 'Ginger Beer', 'Root Beer', 'Orange Soda',
    'Grape Soda', 'Ice Tea', 'Lemonade',
    'Fruit Punch', 'Energy Drink', 'Sports Drink',
  ],
  mocktail: [
    'Shirley Temple', 'Roy Rogers', 'Virgin Mojito', 'Virgin Margarita',
    'Virgin Mary', 'Virgin Piña Colada', 'Virgin Daiquiri',
    'Arnold Palmer', 'Safe on the Beach', 'No-Groni',
  ],
  non_alcoholic: [
    'Non-Alcoholic Beer', '0.0% Lager', 'NA IPA', 'NA Stout',
    'Non-Alcoholic Wine', 'Non-Alcoholic Sparkling Wine',
    'Alcohol-Free Spirit', 'NA Gin Alternative', 'NA Whiskey Alternative',
    'Kombucha',
  ],
  other: [
    'House Special', 'Mixed Drink', 'Signature Cocktail',
    'Hard Tea', 'Hard Lemonade', 'Hard Kombucha',
    'Canned Cocktail', 'RTD Cocktail',
  ],
};

export const DRINK_BRANDS: Record<DrinkType, string[]> = {
  beer: [
    'Guinness', 'Heineken', 'Stella Artois', 'Budweiser', 'Bud Light',
    'Coors Light', 'Miller Lite', 'Miller High Life',
    'Corona', 'Corona Light', 'Modelo Especial', 'Modelo Negra',
    'Dos Equis', 'Pacifico', 'Victoria',
    'Blue Moon', 'Samuel Adams', 'Sierra Nevada', 'Stone Brewing',
    'Dogfish Head', 'Founders Brewing', 'New Belgium', 'Goose Island',
    'Lagunitas', 'Bell\'s Brewery', 'Brooklyn Brewery', 'Anchor Brewing',
    'Yuengling', 'Pabst Blue Ribbon', 'Narragansett',
    'Carlsberg', 'Tuborg', 'Asahi', 'Sapporo', 'Kirin', 'Suntory',
    'Tiger', 'Singha', 'Chang', 'Tsingtao', 'Yanjing',
    'Peroni', 'Birra Moretti', 'Nastro Azzurro',
    'Hoegaarden', 'Leffe', 'Duvel', 'Chimay', 'Orval', 'Westmalle',
    'Weihenstephaner', 'Paulaner', 'Erdinger', 'Franziskaner',
    'BrewDog', 'Meantime', 'Camden Town', 'Beavertown',
    'Foster\'s', 'Victoria Bitter', 'Coopers', 'XXXX Gold',
    'Kingfisher', 'Cobra',
  ],
  wine: [
    'Barefoot', 'Yellow Tail', 'Franzia', 'Josh Cellars',
    'Kim Crawford', 'Santa Margherita', 'La Marca',
    'Meiomi', 'Robert Mondavi', 'Beringer', 'Sonoma-Cutrer',
    'Caymus', 'Silver Oak', 'Rombauer', 'Kendall-Jackson',
    'Stags\' Leap', 'Flowers', 'Duckhorn', 'Matua',
    'Cloudy Bay', 'Whispering Angel', 'Château Ste. Michelle',
    'William Hill', 'Penfolds', 'Jacob\'s Creek', 'Wolf Blass',
    'Veuve Clicquot', 'Moët & Chandon', 'Dom Pérignon', 'Krug',
    'Ruinart', 'Billecart-Salmon', 'Pol Roger',
    'Santa Margherita', 'Antinori', 'Gaja', 'Sassicaia',
    'DAOU', 'Jordan', 'Opus One', 'Screaming Eagle',
    'Château Margaux', 'Château Pétrus', 'Mouton Rothschild',
    'Concha y Toro', 'Montes', 'Santa Rita',
    'Torres', 'Marqués de Riscal', 'Vega Sicilia',
    'Planeta', 'Donnafugata',
  ],
  cocktail: [
    'Bacardi', 'Captain Morgan', 'Don Julio', 'Patrón',
    'Hendrick\'s', 'Tanqueray', 'Bombay Sapphire', 'Beefeater',
    'Grey Goose', 'Ketel One', 'Absolut', 'Tito\'s',
    'Jack Daniel\'s', 'Maker\'s Mark', 'Bulleit',
    'Aperol', 'Campari', 'Cointreau', 'Grand Marnier',
    'Kahlúa', 'Baileys', 'Malibu', 'Midori',
    'Jägermeister', 'Fireball', 'Southern Comfort',
    'Martini & Rossi', 'Noilly Prat', 'Dolin',
  ],
  spirit: [
    'Jack Daniel\'s', 'Jim Beam', 'Wild Turkey', 'Maker\'s Mark',
    'Buffalo Trace', 'Woodford Reserve', 'Bulleit', 'Four Roses',
    'Knob Creek', 'Basil Hayden\'s', 'Larceny', 'Elijah Craig',
    'Blanton\'s', 'Angel\'s Envy', 'Jefferson\'s', 'W.L. Weller',
    'Eagle Rare', 'Pappy Van Winkle',
    'Glenfiddich', 'The Macallan', 'The Glenlivet', 'Laphroaig',
    'Balvenie', 'Talisker', 'Oban', 'Highland Park',
    'Glenmorangie', 'Dalmore', 'Bowmore', 'Ardbeg', 'Lagavulin',
    'Jameson', 'Bushmills', 'Redbreast', 'Tullamore D.E.W.',
    'Green Spot', 'Yellow Spot', 'Powers',
    'Grey Goose', 'Belvedere', 'Ketel One', 'Absolut',
    'Smirnoff', 'Tito\'s', 'Stolichnaya', 'Crystal Head',
    'Hendrick\'s', 'Tanqueray', 'Bombay Sapphire', 'Beefeater',
    'Monkey 47', 'Aviation', 'Roku', 'The Botanist',
    'Bacardi', 'Captain Morgan', 'Havana Club', 'Mount Gay',
    'Plantation', 'Diplomatico', 'Ron Zacapa', 'Appleton Estate',
    'Don Julio', 'Patrón', 'Casamigos', 'Clase Azul',
    'Herradura', 'El Jimador', 'Espolòn', 'Fortaleza',
    'Del Maguey', 'Mezcal Vago', 'Banhez', 'Alipús',
    'Hennessy', 'Rémy Martin', 'Courvoisier', 'Martell',
    'Hine', 'Delamain', 'Bertoux',
    'Suntory Toki', 'Nikka', 'Yamazaki', 'Hibiki',
  ],
  cider: [
    'Angry Orchard', 'Strongbow', 'Woodchuck', 'Magners',
    'Bulmers', 'Rekorderlig', 'Kopparberg', 'Somersby',
    'Stella Artois Cidre', 'Crispin', 'Blake\'s',
    'Original Sin', 'Wyder\'s', 'Ace Cider',
    'Austin Eastciders', 'Bantam Cider', 'Citizen Cider',
    'Artifact Cider', 'Shacksbury', 'Farnum Hill',
  ],
  seltzer: [
    'White Claw', 'Truly Hard Seltzer', 'Bud Light Seltzer',
    'Corona Hard Seltzer', 'Vizzy', 'High Noon',
    'Cacti', 'Lone River Ranch Water', 'Press Hard Seltzer',
    'Wild Basin', 'Crook & Marker', 'Flying Embers',
    'Arctic Summer', 'Social Lite', 'Coors Seltzer',
    'Michelob Ultra Organic Seltzer', 'Natural Light Seltzer',
  ],
  water: [
    'Fiji', 'Evian', 'Voss', 'San Pellegrino', 'Perrier',
    'Aquafina', 'Dasani', 'SmartWater', 'Poland Spring',
    'Essentia', 'Core Hydration', 'Liquid Death',
  ],
  soft_drink: [
    'Coca-Cola', 'Pepsi', 'Dr Pepper', 'Sprite', 'Mountain Dew',
    '7-Up', 'Fanta', 'Schweppes', 'Canada Dry', 'Vernors',
    'Fever-Tree', 'Q Mixers', 'Red Bull', 'Monster', 'Gatorade',
  ],
  mocktail: [
    'Seedlip', 'Lyre\'s', 'Ritual Zero Proof', 'Ghia',
    'Kin Euphorics', 'Optimist Botanicals', 'Spiritless',
  ],
  non_alcoholic: [
    'Heineken 0.0', 'Athletic Brewing', 'BrewDog AF', 'Guinness 0.0',
    'Budweiser Zero', 'Stella Artois Liberté', 'Lagunitas IPNA',
    'Brooklyn Special Effects', 'Clausthaler', 'Erdinger Alkoholfrei',
    'Tost', 'Fre', 'Giesen 0%',
  ],
  other: [],
};
